### ISSUE TITLE
I only generated three files after fine-tuning, is it correct? Why is there no tokenizer.json file?

### ISSUE THREAD

**Issue by chen-lee-li** [loubnabnl/santacoder-finetuning#17]
![image](https://github.com/loubnabnl/santacoder-finetuning/assets/110437811/c818c4ff-592a-407f-b123-d90cf0a7972f)

**Comment by loubnabnl** [comment]
Yes that's expected you can get the tokenizer files from SantaCoder's repo (see [readme](https://github.com/loubnabnl/santacoder-finetuning#how-to-upload-my-trained-checkpoint))
