### ISSUE TITLE
moving a fine tuned model to gpt_bigcode

### ISSUE THREAD

**Issue by Vipitis** [loubnabnl/santacoder-finetuning#20]
Hey,

A while ago I finetuned three models starting with the main sanatacoder model. That one requires `trust_remote_code=True` due to the custom modelling files. GPT-bigcode has been native in `transformers` for a while and I have also seen and used the gpt_bigcode variant of santacoder. 
Now my question is: can I turn my models into natively supported variant too? If so, do you happen to have a script or at least some pointers?

**Comment by loubnabnl** [comment]
We converted each model separately from Megatron-LM but we don't have a script to go from one transformers implementation to the other or from your transformers checkpoint back to Megatron-LM, sorry!

**Comment by Vipitis** [comment]
alright, I will look into it myself
