### ISSUE TITLE
FIM Evaluation

### ISSUE THREAD

**Issue by Hambaobao** [loubnabnl/santacoder-finetuning#26]
Hello, thanks a lot for your great work.
Could you kindly advise on how to replicate the evaluation results of FIM as shown in `Table 6` of your [paper](https://arxiv.org/pdf/2301.03988.pdf)? I've been searching for the evaluation code for quite some time but haven't been able to find it.
<img width="1238" alt="Xnip2024-02-29_21-19-23" src="https://github.com/loubnabnl/santacoder-finetuning/assets/48345096/6d7e0055-d9a9-4ac5-ade8-934a9297de9a">

**Comment by Yoona12** [comment]
你好，请问你解决这个问题了吗？ 能不能分享一下这个代码呢？谢谢
