### ISSUE TITLE
Finetuning on multiple language

### ISSUE THREAD

**Issue by windspirit95** [loubnabnl/santacoder-finetuning#4]
Hi,
I am wondering if it is possible to load dataset from multiple languages (c-sharp, python) for finetuning? Do I need to modify code to do that? Thank you ^^

**Comment by loubnabnl** [comment]
Hi you can load multiple data subsets at the same time by changing `data_dir` in `load_dataset` [here](https://github.com/loubnabnl/santacoder-finetuning/blob/e386e949826913a6571566dee65e7618914f546d/train.py#L137) to a list passed to `data_files`:
```python
dataset = load_dataset(
       'bigcode/the-stack',
        data_files=["data/c-sharp/*", "data/python/*"]
        split=args.split,
        use_auth_token=True,
        num_proc=args.num_workers if not args.streaming else None,
        streaming=args.streaming,
    )
```
But note that the model might have trouble generalizing to multiple languages at the same time (+it was already pre-trained on python).

**Comment by windspirit95** [comment]
Thank you for your help 👍
